version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Exposes MongoDB port
    volumes:
      - ./src/main/resources/data-mongo.js:/docker-entrypoint-initdb.d/data-mongo.js  # Initialization script
    networks:
      - app-network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI= mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./banking-frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"  # Exposes frontend on port 8082
    depends_on:
      - application
    networks:
      - app-network


networks:
  app-network:
    driver: bridge