openapi: 3.0.3
info:
  title: Banking API
  description: API for managing bank accounts and transactions
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /open-account:
    post:
      summary: Open a new account for an existing customer
      description: Creates a new current account and optionally deposits an initial credit amount.
      operationId: openAccount
      security:
        - basicAuth: []
      parameters:
        - name: customerID
          in: query
          required: true
          description: ID of the customer
          schema:
            type: string
            format: uuid
        - name: initialCredit
          in: query
          required: true
          description: Initial deposit amount
          schema:
            type: number
            format: double
            minimum: 0
      responses:
        "201":
          description: Account successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "400":
          description: Invalid request (e.g., customer not found)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /customer/{customerID}:
    get:
      summary: Get customer details
      description: Retrieves customer information, including accounts and transactions.
      operationId: getCustomerDetails
      security:
        - basicAuth: []
      parameters:
        - name: customerID
          in: path
          required: true
          description: ID of the customer
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Customer details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDetails"
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    Account:
      type: object
      properties:
        accountID:
          type: string
          format: uuid
        customerID:
          type: string
          format: uuid
        balance:
          type: number
          format: double
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/Transaction"

    Transaction:
      type: object
      properties:
        transactionID:
          type: string
          format: uuid
        accountID:
          type: string
          format: uuid
        amount:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          enum: [SUCCESS, FAILED, PENDING]

    CustomerDetails:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: Unique error code
        message:
          type: string
          description: Error message

  responses:
    ErrorResponse:
      description: Error response structure
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
