openapi: 3.0.1
info:
  title: Delivery API
  description: API for managing deliveries
  version: 1.0.0
paths:
  api/v1/deliveries:
    post:
      summary: Create a new delivery
      description: Creates a new delivery based on the provided delivery request.
      operationId: createDelivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryRequest'
      responses:
        '201':
          description: Delivery created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: Invalid input
  api/v1/deliveries/invoice:
    post:
      summary: Send invoices
      description: Sends invoices for the specified delivery IDs.
      operationId: sendInvoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceRequest'
      responses:
        '200':
          description: Invoices sent successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MockInvoiceResponse'
        '400':
          description: Invalid input
  api/v1/deliveries/business-summary:
    get:
      summary: Get business summary
      description: Generates a business summary for yesterday's deliveries.
      operationId: getBusinessSummary
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Business summary generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessSummaryPage'
components:
  schemas:
    DeliveryRequest:
      type: object
      properties:
        vehicleId:
          type: string
    Delivery:
      type: object
      properties:
        id:
          type: string
        
    InvoiceRequest:
      type: object
      properties:
        deliveryIds:
          type: array
          items:
            type: string
    MockInvoiceResponse:
      type: object
      properties:
        invoiceId:
          type: string
    BusinessSummaryPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/BusinessSummary'
        totalPages:
          type: integer
        totalElements:
          type: integer
    BusinessSummary:
      type: object
      properties:
